### PR TITLE
Fix: react deprecation, imports, and update packages

### PR DESCRIPTION
**Pull request by mikehardy**
Hi there @davidgovea!

Thanks for picking up this frequently dropped package :-)

I needed a quick alternative to the android datepicker which was unfortunately confusing my users and saw this as a great fit.

The README/Demo needed an update for your new name-scoped npmjs.com publish though I think? And I saw that the react lifecycle method deprecations at least needed a temporary change, then figured I'd update packages while I was at it.

There is still a conversion to the lean-core iOS datepicker namespace to do but that only shows up in tests on my usage, so I think this at least has the package nice and quiet for the moment.

Tested in my previously working app from the 3rd fork, migrated to yours, and then with my patch integrated, along with the `npm test` from package.json::scripts, so hopefully this works?

Cheers

### CODE REVIEW

**Comment by davidgovea** [comment]
Thanks @mikehardy! Merged & published `v0.0.231` -- I'll be switching over to proper semver soon :)

Thanks for the tip on the lean-core extraction too -- will start looking around at how to handle backward-compat, or whether we'll just have to force apps to use the extracted datepicker, with whatever RN version constraints that comes with

**Comment by mikehardy** [comment]
Happy to help - w.r.t. iOS, I dunno, does it make sense to even ingest the change vs just booting iOS out? is there value in an android wheel date picker just wrapping the iOS one or can people do a platform check? 🤔 If I were going to continue wrapping it I'd just get everything patched up great, issue a 1.0, then about immediately switch to the new one and do a v2 breaking change 🤷‍♂ . In my experience on react-native-device-info people are okay ingesting breaking changes as long as they are very visible, clearly explained, and have a suggested specific migration. I doubt anyone would really care either way then

**Comment by davidgovea** [comment]
I agree -- the iOS wrapping seems to exist for integrating custom pickers on ios (via [this lib](https://github.com/pinguinjkeke/react-native-custom-datepicker-ios)).

I'm not using that feature, and it even mentions possible appstore rejection, so that, plus the lean-core philosophy is more reason to leave it behind. Could rename the project `react-native-android-wheel-datepicker` or something

**Comment by mikehardy** [comment]
that would be reasonable, to me

**Pull request merged**
