### PR TITLE
Ajustado o DatePicker do Android para meses por extenso conforme o do iOS

### PR DESCRIPTION
**Pull request by mrfrigerio**

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
I could never personally agree to this with no ability to change local, perhaps an integration with https://github.com/react-native-community/react-native-localize but even then would be better if it was optional

**Comment by davidgovea** [comment]
Thanks for submitting this PR @mrfrigerio!

I won't be merging it in as-is for reasons mentioned by @mikehardy, but you have identified a shortcoming of the labeling capabilities.

`labelUnit` is not enough; it would be nice to be able to pass in custom labels (or a formatter function), allowing users to hook in to whatever date/i18n solution they are using. Moment vs. Date-fns vs. luxon choices should happen outside of this library.

I'll be splitting this repo out shortly, so that the "Issues" feature can be used. Until then, I'll leave this open.

**Comment by davidgovea** [comment]
Looks like this is a common reason to fork: https://github.com/bFIT-Team/react-native-wheel-datepicker/commit/1c262787709de8ab6ab501d5ec334919c23cbb71

Can probably make some time this weekend to make some improvements.

**Comment by davidgovea** [comment]
Issue to discuss this goal opened: #16 

Closing PR

**Pull request closed without merging**
